fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.2.2
    selinux: git://github.com/treydock/puppet-selinux.git
  symlinks:
    site_selinux: "#{source_dir}"
